// Built-in default dock layout for Map Forge — auto-captured from the
// maintainer's "Set as default" arrangement (2026-06-03, layout v5).
//
// buildDefaultLayout() applies this for Reset + fresh sessions WHEN its
// `v` matches LAYOUT_VERSION (a user's own "Set as default" still wins;
// the procedural layout is the fallback). To refresh after a panel-set
// change: arrange the dock, "Set as default", fully exit Merc Forge,
// re-run the layout-capture step, and repaste the JSON here.
export const BUILT_IN_DEFAULT_LAYOUT_JSON =
  '{"v":5,"layout":{"grid":{"root":{"type":"branch","data":[{"type":"branch","data":[{"type":"leaf","data":{"views":["palette","assets","tilesetViewer"],"activeView":"tilesetViewer","id":"2"},"size":685},{"type":"leaf","data":{"views":["variants"],"activeView":"variants","id":"3"},"size":260}],"size":220},{"type":"branch","data":[{"type":"branch","data":[{"type":"leaf","data":{"views":["layers"],"activeView":"layers","id":"6"},"size":279},{"type":"leaf","data":{"views":["view"],"activeView":"view","id":"10"},"size":696},{"type":"leaf","data":{"views":["tool"],"activeView":"tool","id":"5"},"size":2253}],"size":107},{"type":"leaf","data":{"views":["canvas"],"activeView":"canvas","id":"1"},"size":738},{"type":"leaf","data":{"views":["log"],"activeView":"log","id":"11"},"size":100}],"size":3228},{"type":"leaf","data":{"views":["inspector"],"activeView":"inspector","id":"4"},"size":360}],"size":945},"width":3808,"height":945,"orientation":"HORIZONTAL"},"panels":{"palette":{"id":"palette","contentComponent":"default","title":"Palette"},"assets":{"id":"assets","contentComponent":"default","title":"Browse Assets"},"tilesetViewer":{"id":"tilesetViewer","contentComponent":"default","title":"Tileset Viewer"},"variants":{"id":"variants","contentComponent":"default","title":"Variants"},"layers":{"id":"layers","contentComponent":"default","title":"Layers"},"tool":{"id":"tool","contentComponent":"default","title":"Tool"},"canvas":{"id":"canvas","contentComponent":"default","title":"Canvas"},"inspector":{"id":"inspector","contentComponent":"default","title":"Inspector"},"view":{"id":"view","contentComponent":"default","title":"View"},"log":{"id":"log","contentComponent":"default","title":"Log"}},"activeGroup":"1"}}';
